### ISSUE TITLE
mPDF 6.x PHP 7.1 incompatibility 

### ISSUE THREAD

**Issue by baselbers** [baselbers/woocommerce-pdf-invoices#133]

**Comment by stuffo** [comment]
mpdf v6.1.3 works without throwing a lot of these:

`` PHP Warning:  Illegal string offset 'ID' in /xxx/wp-content/plugins/woocommerce-pdf-invoices/lib/mpdf/classes/cssmgr.php on line 1355   
PHP Warning:  Illegal string offset 'LANG' in /xxx/wp-content/plugins/woocommerce-pdf-invoices/lib/mpdf/classes/cssmgr.php on line 1355   
PHP Warning:  A non-numeric value encountered in /xxx/wegamed-wp/wp-ontent/plugins/woocommerce/includes/admin/wc-admin-functions.php on line 352  
``

This warnings get dumped into the PDF too and make certain PDF viewers (eq qpdfview) think the PDF is broken.

**Comment by baselbers** [comment]
https://github.com/baselbers/woocommerce-pdf-invoices/commit/b87025c9068edbb1c8d883124d01694aeee45c71
