### ISSUE TITLE
Bug: Wrong invoice date and number shown on the Order details page

### ISSUE THREAD

**Issue by girogiro** [baselbers/woocommerce-pdf-invoices#136]
Curent date is shown nearby PDF invoice action butons on the Order details page instead of the date when the invoice was issued.

IMHO there is a bug in `BEWPI_Abstract_Invoice.get_formated_invoice_date()` method that returns current date instead of the invoice date.

The same holds for `Y`, `y` and `m` fields in the invoice number. `BEWPI_Abstract_Invoice.get_formatted_number()` replaces them by current year/month instead of invoice's one.

**Comment by baselbers** [comment]
bcb32ec14e453ac3bcda6cd124c03f7cd92912d7
