### ISSUE TITLE
Bug: wrong displayed invoice number

### ISSUE THREAD

**Issue by girogiro** [baselbers/woocommerce-pdf-invoices#142]
The bug #136 still persists.

Invoice date is stored in the database as formatted string, there is no need to convert in anymore before printing. Also, `strtotime` can't process custom formats the stored date can be formatted and a different way of extracting year or month from the stored date is need.

Pull request #141 fixes it.

**Comment by baselbers** [comment]
Thanks @girogiro.
Was already busy with a minor update.
Improved date formatting in database by updating formatted date postmeta called '_bewpi_invoice_date' to hold mysql date. This way formatting won't be a problem anymore (from now on).
