### ISSUE TITLE
Update routine for versions <= 2.6.1 fails to create path postmeta under certain conditions

### ISSUE THREAD

**Issue by EmilEriksen** [baselbers/woocommerce-pdf-invoices#159]
After pushing a new release, which included this update, to production yesterday, all our old invoices appeared to be missing. They were still in the uploads folder but didn't show up in the admin area because the `_bewpi_invoice_pdf_path` postmeta wasn't created in the update routine. After doing a little digging I found the culprit to be [here](https://github.com/baselbers/woocommerce-pdf-invoices/blob/master/bootstrap.php#L144). This option was **not** enabled (and has never been tinkered with) on our site but our invoices were still located in year folders in the uploads dir. This caused the update routine to fail since it only looks for PDFs in `BEWPI_INVOICES_DIR` and not in year folders when `bewpi_reset_counter_yearly` is false.

I've resolved the issue on our site but I wanted to let you know.

**Comment by baselbers** [comment]
Thanks for pointing that out. Will be fixed in next update.

**Comment by baselbers** [comment]
https://github.com/baselbers/woocommerce-pdf-invoices/commit/0fedfc67d90ba3d84a5f4634ff1d801c448bcca9
