### ISSUE TITLE
Files in lib/mpdf/ttfontdata missing from 2.6.4 release on WordPress.org

### ISSUE THREAD

**Issue by EmilEriksen** [baselbers/woocommerce-pdf-invoices#163]
While doing an rsync command today I noticed these files are missing from [2.6.4](https://downloads.wordpress.org/plugin/woocommerce-pdf-invoices.2.6.4.zip) specifically. The files seem to have been left unchanged after updating the plugin on my site and I'm not experiencing any issues but I just wanted to point it out in case it could potentially cause issues.

**Comment by baselbers** [comment]
Updated to 2.7.1. This should be fixed now. Thanks for letting me know. Let me know if the problem still occurs.
