### ISSUE TITLE
setup_directories() run on each admin page load and GLOB_BRACE unsupported on some systems

### ISSUE THREAD

**Issue by EmilEriksen** [baselbers/woocommerce-pdf-invoices#166]
After updating this plugin today on my local Docker environment I got a few PHP errors since GLOB_BRACE (which is used [here](https://github.com/baselbers/woocommerce-pdf-invoices/blob/master/includes/be-woocommerce-pdf-invoices.php#L152)) is not supported on some systems including Alpine Linux which many Docker containers run ([issue](https://github.com/zendframework/zend-stdlib/issues/58)). This can easily be fixed with something along the lines of `$font_files = array_merge( glob( WPI_DIR . '/tmp/fonts/*.ttf' ), glob( WPI_DIR . '/tmp/fonts/*.otf' ) );`.

I realise this is probably an edge case but what concerns me more is that the entire setup_directories() function is run on each admin page load. Seems a little excessive to me that these kinds of file operations are run on each page load in admin.

**Comment by baselbers** [comment]
dc22acf0e9970474e404fe0f9686bae9f8867ba8
926cc7f100180c26d49b0dcdf99b07e38782f86c
