### ISSUE TITLE
[2.7.3] Missing $order parameter in bewpi_get_id()

### ISSUE THREAD

**Issue by EmilEriksen** [baselbers/woocommerce-pdf-invoices#168]
[Here](https://github.com/baselbers/woocommerce-pdf-invoices/blob/master/includes/functions.php#L18). I'm getting a warning `ReflectionProperty::getValue() expects exactly 1 parameter, 0 given`. Passing $order to the function works.

This completely breaks plugin functionality (on my setup anyway).

**Comment by baselbers** [comment]
I've fixed it and will update as soon as possible. What PHP version do you have? Very strange I do not get this error.

**Comment by EmilEriksen** [comment]
Sounds great! I'm on 7.0.17. According to the PHP manual the function expects the $object parameter if the property is non-static:
> If the property is non-static an object must be provided to fetch the property from.

**Comment by baselbers** [comment]
https://github.com/baselbers/woocommerce-pdf-invoices/commit/28066788fed26a7cef3d214977118899dd86d104
