### ISSUE TITLE
Micro template Issues from 2.6.0. The tax rate title is twice

### ISSUE THREAD

**Issue by Teresa-In** [baselbers/woocommerce-pdf-invoices#169]
There is a problem with the micro template from 2.6.0 version, the percentage of the taxes title is repeated, also when there are different taxes in two columns is shown the column filled with zeros

In the previous version 2.5.7 of the micro template the tax rate title it was good, moreover when the tax was zero did not appear.

I guess it's simple to fix but I do not have php knowledge. I also do not find someone who happens to have the same problem

**Comment by baselbers** [comment]
@Teresa-In please use the WordPress Support forum for these kind of questions.
