### ISSUE TITLE
Option to change the invoice totals due to different tax regulations per country

### ISSUE THREAD

**Issue by baselbers** [baselbers/woocommerce-pdf-invoices#170]

**Comment by baselbers** [comment]
👍

**Comment by baselbers** [comment]
👍

**Comment by baselbers** [comment]
👍

**Comment by baselbers** [comment]
👍

**Comment by frucomerci** [comment]
Hi Bas!

A part of having the order changed its very important that the SUBTOTAL label adds the shipping cost (without VAT) to the product sum.

They are requirements related to Spanish Tax, and invoice table should look like this:

Product × 1	76,09€
Shipping cost	4,96€
Subtotal	81,05€ 
VAT 10% (product) 7,61€
VAT 21% (shipping)	1,04€
Total	89,70€

Many thanks!

**Comment by baselbers** [comment]
👍

**Comment by baselbers** [comment]
👍

**Comment by baselbers** [comment]
👍
