### ISSUE TITLE
Error when checkout

### ISSUE THREAD

**Issue by Puripong458** [baselbers/woocommerce-pdf-invoices#171]
Hi,

I found an issue with recent Woocommerce update and your plugin.  (Free version)  I have an issue when checkout and got this message.

SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data

I have turn-on off for each plugin and see which one caused the issue.  Finally I found it because of your plugin.  When I disabled your plugin the checkout problem was vanished.  Your plugin works fine until the recent update from Woocommerce and now this message appeared.  

While I may switch to other plugin but I do like your quality plugin very much.  Could you please take a look?  This could help others that has a similar issue like me as well.

Regards,
Puripong

**Comment by baselbers** [comment]
Hi,

Can you enable debugging and send me your debug.log file?

**Comment by Puripong458** [comment]
Here you are.  

[debug.zip](https://github.com/baselbers/woocommerce-pdf-invoices/files/992720/debug.zip)

**Comment by baselbers** [comment]
'[11-May-2017 10:37:29 UTC] PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 32 bytes)'

How many memory do you allocate? You need to [increase it](https://docs.woocommerce.com/document/increasing-the-wordpress-memory-limit/).

**Comment by Puripong458** [comment]
The current WP memory limit is 256 MB according to Woocommerce system status.  It it already sufficient?  Do I need to allocate more?

**Comment by baselbers** [comment]
That really depends on how many plugins you are using. Try 384 MB.
