### ISSUE TITLE
No longer works with sequential order numbers plugin?

### ISSUE THREAD

**Issue by shawaj** [baselbers/woocommerce-pdf-invoices#183]
Displays the wrong invoice numbers when using the sequential order numbers plugin.

It uses the “post id” as the invoice number, not the actual order number provided by sequential order numbers. 

And it also does not seem to organise them by year anymore?

This started happening in around February, after an update, before that it worked fine. Can it be fixed?

Thanks

**Comment by shawaj** [comment]
Posted on the support forum also - https://wordpress.org/support/topic/no-longer-works-with-sequential-order-numbers-plugin/

**Comment by baselbers** [comment]
Will be fixed in version 2.9.1.
https://github.com/baselbers/woocommerce-pdf-invoices/commit/cafe79a6a0f1fa4438b5c7e5fdce6fa4f23a34dc

**Comment by baselbers** [comment]
Will close issue. You can use the support forum to reply.

**Comment by shawaj** [comment]
Thanks @baselbers
