### ISSUE TITLE
vendor/mpdf/mpdf/ttfontdata/ is empty as of 2.9.0

### ISSUE THREAD

**Issue by ablears** [baselbers/woocommerce-pdf-invoices#184]
Getting a bunch of warnings like this:

`[15-May-2017 23:37:10 UTC] PHP Warning:  file_put_contents(/var/www/xx/wp-content/plugins/woocommerce-pdf-invoices/vendor/mpdf/mpdf/ttfontdata/dejavusanscondensed.GSUB.nko .DFLT.php): failed to open stream: Permission denied in /var/www/xx/wp-content/plugins/woocommerce-pdf-invoices/vendor/mpdf/mpdf/classes/ttfontsuni.php on line 2318`

Looking at the plugin folders I can see vendor/mpdf/mpdf/ttfontdata/ is empty.

Without the font data I get another warning:

`[16-May-2017 00:40:21 UTC] PHP Warning:  Transactional email triggered fatal error for callback woocommerce_email_attachments in /var/www/xx/wp-content/plugins/woocommerce/includes/class-wc-emails.php on line 153`

No email is sent.

So I grabbed mpdf/ttfontdata from another source and now it works.

**Comment by baselbers** [comment]
Thanks.

Busy with it at the moment. Next update will get fix for this.
https://github.com/baselbers/woocommerce-pdf-invoices/commit/505265557d248dd672b37c16dcfcc0369372fc04

**Comment by baselbers** [comment]
https://github.com/baselbers/woocommerce-pdf-invoices/blob/master/includes/abstracts/abstract-document.php#L93
