### ISSUE TITLE
Cannot complete checkout 

### ISSUE THREAD

**Issue by ablears** [baselbers/woocommerce-pdf-invoices#186]
In Version 2.9.0 I'm unable to check out on one of my staging sites.

I see about 50 of these warnings in the logs when I select a payment method and try to complete checkout:

`PHP Warning:  A non-numeric value encountered in /var/www/xx/wp-content/plugins/woocommerce-pdf-invoices/vendor/mpdf/mpdf/mpdf.php on line 30591`

Strangely I do get the order email with PDF invoice attached, but checkout errors with an empty WooCommerce error box and doesn't redirect to the order received page.

![image](https://cloud.githubusercontent.com/assets/3182580/26228842/1671ddde-3c91-11e7-94b4-52172a81e113.png)

`
### WordPress Environment ###

Home URL: http://uk-barcodes.co.uk/wooapi
Site URL: http://uk-barcodes.co.uk/wooapi
WC Version: 3.0.7
Log Directory Writable: ✔
WP Version: 4.7.5
WP Multisite: ✔
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 7.1.2-1+0~20170217124815.15+jessie~1.gbp510ca7
PHP Post Max Size: 16 MB
PHP Time Limit: 120
PHP Max Input Vars: 5000
cURL Version: 7.38.0
OpenSSL/1.0.1t

SUHOSIN Installed: –
MySQL Version: 5.7.17
Max Upload Size: 1 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.7
WC Database Prefix: wpintbnet_66_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (21) ###

Cookie Consent: by Catapult_Themes – 2.3.2
WooCommerce Dynamic Pricing & Discounts: by RightPress – 1.1.2
WooCommerce Ajax Add To Cart (oraksoft): by Karapet Abrahamyan – 1.0.0
WooCommerce - Autocomplete Orders: by Serious Plugins – 1.1.4
WooCommerce PayPal Express Checkout Gateway: by WooCommerce – 1.2.1
WooCommerce Stripe Gateway: by WooCommerce – 3.1.8
WooCommerce PDF Invoices: by Bas Elbers – 2.9.0
WooCommerce - Store Exporter Deluxe: by Visser Labs – 2.2.2
WooCommerce: by Automattic – 3.0.7
Query Monitor: by John Blackbourn – 2.13.4
WooCommerce Helper: by WooCommerce – 1.7.2 – Network enabled
Blog Copier: by Modern Tribe
Inc. – 1.0.7

Custom_Meta: by TODO – 1.0.0
Fast Secure Contact Form: by Mike Challis
Ken Carlson – 4.0.50

SSL Insecure Content Fixer: by WebAware – 2.4.0
WordPress MU Domain Mapping: by Donncha O Caoimh – 0.5.5.1
WP eCommerce Payment Method notifications fix: by WebAware –
Wordfence Security: by Wordfence – 6.3.9
WP SEO Structured Data Schema: by kcseopro – 2.0
Woo Data Updater: by Mehul Kaklotar – 1.0
FG Fix Serialized Strings: by Frédéric GILLES – 1.1.2

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: NZD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 0
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #354 - /shop/
Cart: #1399717 - /cart/
Checkout: #1399718 - /checkout/
My account: #1399719 - /my-account/

### Theme ###

Name: Storefront
Version: 2.1.8
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: –

### Templates ###

Scheduled Export to FTP: ✔
Scheduled Export to SFTP: ✔
`

**Comment by baselbers** [comment]
Hi,

You can try version 2.9.1 which should fix this issue. Let me know if it works.

**Comment by ablears** [comment]
Thank you, it works for me :)
