### ISSUE TITLE
Make visible columns settings visible based on template type (B2B & B2C)

### ISSUE THREAD

**Issue by baselbers** [baselbers/woocommerce-pdf-invoices#190]
https://wordpress.org/support/topic/filter-for-invoice-columns/

**Comment by mjke87** [comment]
The main problem is, that the `template_options` get loaded only once, early on, and are static thereafter. Perhaps creating a `get_template_options` function that takes the option key as parameter would be a possible solution. Inside of this function we could introduce a filter. This would allow to filter any kind of template option, dynamically.

**Comment by baselbers** [comment]
I will make sure that there will be a filter within below method.
https://github.com/baselbers/woocommerce-pdf-invoices/blob/v2.9.1/includes/woocommerce-pdf-invoices.php#L727

**Comment by baselbers** [comment]
As of version 2.9.2 it will be able to change option value. For example when getting the customer notes.

```
if ( WPI()->get_option( 'template', 'show_customer_notes' ) ) {
echo "This is a customer note";
}
```

Use filter like below to change the option value for specific order or invoice data using `WPI()->templater()`.

```
function disable_customer_notes( $option ) {
	$order = WPI()->templater()->get_order();

	if ( $order ) {
		// Do something with order or templater.
		$option = 0;
	}

	return $option;
}
add_filter( 'bewpi_pre_option-template-show_customer_notes', 'disable_customer_notes' );
```

**Comment by girivasanit2sbc** [comment]
How to add Customer email in invoce
