### ISSUE TITLE
Invoices are being regenerated when viewed

### ISSUE THREAD

**Issue by EmilEriksen** [baselbers/woocommerce-pdf-invoices#203]
After changing some settings today, I noticed that when I tried viewing old invoices, they were actually being regenerated according to the new settings. As far as I'm aware, you're supposed to keep the exact copy that was sent to the customer for accounting purposes. This doesn't seem right to me?

**Comment by EmilEriksen** [comment]
Also, after refunding an order it seems like the original invoice is being overwritten with a new invoice where the refunded amount is being displayed. Surely this is what credit notes are for and the original invoice should be left untouched?

**Comment by baselbers** [comment]
You're right. When the invoice has been sent to the customer, it should not be regenerated when viewing.

I will consider to add an "Update" button, so admin can choose to update invoice and alerting admin when invoice already has been sent to customer before proceeding with the update.

**Comment by baselbers** [comment]
836f0d0951116dae8d6ca38c2f57a8c9b109940f
a61d7c180ef2b387d5e3bf80f459c9384b1cecdc
