### ISSUE TITLE
German Translation not working in generated PDFs

### ISSUE THREAD

**Issue by itdahde** [baselbers/woocommerce-pdf-invoices#207]
Hi, 

my issue is following: in checkout and after payment all german translations are well. Only if i create as an admin pdf incoices, the PDF contents are most in english.
So i took a look at the plugin, found lang dir with the full german .mo and .po file. 
![00008-2017-edited](https://user-images.githubusercontent.com/6002033/30288664-e1b1bdaa-9729-11e7-817d-5c4b3071f82b.jpg)

With best Regards from Germany, 
Alex

**Comment by baselbers** [comment]
Hi Alex,

Did you've managed to translate the German file? You can send it to me and I will add it to the next update if you like.

**Comment by itdahde** [comment]
Hi, 

yes, i wrote them, but not local, just in git, i do not know enough about git, to send you this as file. If i got it, i will send you ;) 

Best regards, Alex

**Comment by baselbers** [comment]
Hi Alex,

Can you send me the file? I will add it to the plugin. :)
