### ISSUE TITLE
Unable to skip invoice generation using provided filters

### ISSUE THREAD

**Issue by Xicer** [baselbers/woocommerce-pdf-invoices#209]
Hey. Your documentation states the following to gain control over invoice generation skipping.

```
function bewpi_skip_invoice_generation( $skip, $status, $order ) {
     // Do your stuff based on the order.
 
  return true; // True to skip.
 }
 add_filter( 'bewpi_skip_invoice_generation', 'bewpi_skip_invoice_generation', 10, 3 );
```

But this is your filter (includes/woocommerce-pdf-invoices.php:553):
```
// Skip invoice generation.
$skip = apply_filters( 'bewpi_skip_invoice_generation', false, $status, $order->get_total() );
```

Since you pass in the order total it is not possible to access the order object and check any other order related details.

If I'm actually missing something here, let me know. Thank you and keep it up!

**Comment by baselbers** [comment]
Thanks! This has been fixed.
