### ISSUE TITLE
add possibility to remove item-meta altogether

### ISSUE THREAD

**Issue by acidix** [baselbers/woocommerce-pdf-invoices#211]
https://github.com/baselbers/woocommerce-pdf-invoices/blob/a61d7c180ef2b387d5e3bf80f459c9384b1cecdc/includes/abstracts/abstract-invoice.php#L426

Quick fix: comment line 426, would be nice to add a hook to allow to skip all item meta in invoices

**Comment by baselbers** [comment]
f1e0c1d
