### ISSUE TITLE
Regenerate Invoices No more Available?

### ISSUE THREAD

**Issue by nikhilgoyal** [baselbers/woocommerce-pdf-invoices#215]
Earlier versions of this plugin had an option to re-regenerate invoices, which is a useful feature. How can one enable this option again.

**Comment by baselbers** [comment]
What do you mean with 're-generate'? Update invoice from edit order page? You can change the bewpi_invoice_sent meta to '0' and you will be able to update the invoice.

**Comment by nikhilgoyal** [comment]
By re-generate I mean update the invoice. As sometimes, we are required to make changes to order e.g. customer address. I don't remember now, but after certain woocommerce update, I could not see the `update` invoice option. 

Now that is not the case.

**Comment by baselbers** [comment]
You can change the bewpi_invoice_sent meta to '0' and you will be able to update the invoice.
