### ISSUE TITLE
Manual invoice sending gone?

### ISSUE THREAD

**Issue by eskadesign** [baselbers/woocommerce-pdf-invoices#216]
Hi Bas,

I could have sworn that in the past there was an dropdown option inside the order admin to "Resend customer invoice" to manual resend the invoice to a customer. But it seems it's now impossible?
https://www.dropbox.com/s/02gdoe1uuldiha7/pdf.jpg?dl=0

How do I do that now? 

p.s. I'm using the premium version (1.6.4)

**Comment by baselbers** [comment]
This is a feature from WooCommerce, so they decide to add or remove it.
