### ISSUE TITLE
Fatal error preventing invoice generation on network install

### ISSUE THREAD

**Issue by ablears** [baselbers/woocommerce-pdf-invoices#221]
Hello, on 2.9.10 on a network install I am seeing the following fatal error:

> PHP Fatal error:  Uncaught MpdfException: Can't open file /var/www/zzz/wp-content/uploads/sites/10/sites/10/woocommerce-pdf-invoices/mpdf/ttfontdata/dejavusanscondensed.GSUBGPOStables.dat in /var/www/zzz/wp-content/plugins/woocommerce-pdf-invoices/vendor/mpdf/mpdf/classes/otl.php

This plugin version is creating duplicated paths such as 'uploads/sites/10/sites/10/'

Downgrading to 2.9.9 works OK.

**Comment by baselbers** [comment]
88b054b278710009eedc3c24a6a743da524bd18e
