### ISSUE TITLE
Generated pdf not parsing from external systems!

### ISSUE THREAD

**Issue by gnnpls** [baselbers/woocommerce-pdf-invoices#228]
Hi. Thanks for the great work.
We face a problem with the generated pdfs:
When we try to open them with Office we get the following message:
![image](https://user-images.githubusercontent.com/4531972/33875625-7c782ee8-df2b-11e7-8370-fbdb22fc9008.png)

The thing is for other pdfs file word opens them fine. It's not about office word we need the files to get parsed by another program in order to have ERP integration.

Is something we can do about it?

**Comment by baselbers** [comment]
What encoding does your ERP require?
