### ISSUE TITLE
Unable to Generate Invoice Since 1Jan2018

### ISSUE THREAD

**Issue by eddiegohwj** [baselbers/woocommerce-pdf-invoices#229]
![image](https://user-images.githubusercontent.com/10890966/34475270-601f812e-efc5-11e7-9d5d-1c5c1fcc7524.png)

Hello Fella, Happy New Year
I've purchased the premium version, and has been using without any issue during the past few weeks.

![image](https://user-images.githubusercontent.com/10890966/34475280-88adcf10-efc5-11e7-9c77-f1e9dff70c8c.png)

but right now bulk/ single invoice generation crashes.

**Comment by jjbluesky** [comment]
Same here..

**Comment by bdice** [comment]
I had this problem as well. I resolved it by manually creating the folder `2018` in `wp-content/uploads/woocommerce-pdf-invoices/attachments/` with the same permissions as the folder for `2017`.

**Comment by bdice** [comment]
See also: https://wordpress.org/support/topic/cant-create-a-pdf-invoice-http-error-500/

**Comment by klopina14** [comment]
Where did you add the folder? Where do I find the Content?

**Comment by bdice** [comment]
Go to the root directory of your WordPress installation. Then go to `wp-content/uploads/woocommerce-pdf-invoices/attachments/`. Then create a folder called `2018`. You should see the folder `2017` there as well.
