### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by marcodeheus** [baselbers/woocommerce-pdf-invoices#231]
Fatal error: Uncaught exception 'MpdfException' with message 'Unable to create output file: /home/pogp290887/domains/mijneigennaam.nl/public_html/wp-content/uploads/woocommerce-pdf-invoices/attachments/2018/27200-2018.pdf' in /home/pogp290887/domains/mijneigennaam.nl/public_html/wp-content/plugins/woocommerce-pdf-invoices/vendor/mpdf/mpdf/mpdf.php:9442 Stack trace: #0 /home/pogp290887/domains/mijneigennaam.nl/public_html/wp-content/plugins/woocommerce-pdf-invoices/includes/abstracts/abstract-document.php(204): mPDF->Output('/home/pogp29088...', 'F') #1 /home/pogp290887/domains/mijneigennaam.nl/public_html/wp-content/plugins/woocommerce-pdf-invoices/includes/abstracts/abstract-invoice.php(321): BEWPI_Abstract_Document->generate('F') #2 /home/pogp290887/domains/mijneigennaam.nl/public_html/wp-content/plugins/woocommerce-pdf-invoices/includes/woocommerce-pdf-invoices.php(574): BEWPI_Abstract_Invoice->generate() #3 [internal function]: BE_WooCommerce_PDF_Invoices->attach_invoice_to_email(Array, 'new_order', Object(WC_Order)) #4 /home/pogp29 in /home/pogp290887/domains/mijneigennaam.nl/public_html/wp-content/plugins/woocommerce-pdf-invoices/vendor/mpdf/mpdf/mpdf.php on line 9442

**Comment by bdice** [comment]
I had this same issue. I resolved it by manually creating the folder `2018` in `wp-content/uploads/woocommerce-pdf-invoices/attachments/` with the same permissions as the folder for `2017`. See https://github.com/baselbers/woocommerce-pdf-invoices/issues/229#issuecomment-355573307
