### ISSUE TITLE
ERROR WHEN CHECKOUT

### ISSUE THREAD

**Issue by justharp** [baselbers/woocommerce-pdf-invoices#237]
Fatal error</b>:  Allowed memory size of 41943040 bytes exhausted (tried to allocate 36 bytes) in <b>/home/justfzyx/public_html/wp-content/plugins/woocommerce-pdf-invoices/vendor/mpdf/mpdf/classes/ttfontsuni.php</b> on line <b>4741</b><br />

I had to disable the plugin when checking out i get this error

**Comment by baselbers** [comment]
https://docs.woocommerce.com/document/increasing-the-wordpress-memory-limit/
