### ISSUE TITLE
Trying to view generated PDF invoice “Error: Failed to load PDF Document”

### ISSUE THREAD

**Issue by bobbyrush** [baselbers/woocommerce-pdf-invoices#238]
All was working great but am now facing an issue where generated pdf invoices wont open,  get an Error "Failed to load PDF Document". Seems to work ok with Firefox but no others.

In debug mode I get this error:

Error message detected - PDF file generation aborted.

display_zero_rated_vat is deprecated since version WooCommerce PDF Invoices v2.8 with no alternative available.
File: /var/www/vhosts/****.com.au/wp-includes/functions.php
Line: 3842

**Comment by baselbers** [comment]
You are using the older deprecated template. I can advise to switch to minimal template.
