### ISSUE TITLE
Plugin Produces errors after last Wordpress and woocommerce updates.

### ISSUE THREAD

**Issue by globalbird** [baselbers/woocommerce-pdf-invoices#246]
Hi Guys, just to let you know that I have experienced issues with your plugin after the last WP and woocommerce updates. Running on PHP 7.0 - WP 4.9.8 and WooCom 3.4.4 - Completing an order or create invoice on order page causing error 500 (sorry - site is live, have no more info right now).

**Comment by baselbers** [comment]
Thanks for letting me know. Much appreciate it.
My apologies for my late reply.
