### ISSUE TITLE
Error in Arabic Debugging in user side email 

### ISSUE THREAD

**Issue by SaraAmrousy** [baselbers/woocommerce-pdf-invoices#247]
Hello,
you made a great plugin, but I have only one issue with it in user invoice
For example, a word Like سبتمبر  it appears as س ب ت م ب ر however in admin mail the word appear correct as one linked word not letter
I tried to change the font but still the same
Kindly, Check attached Pdf It will be more clear for you

[admin side.pdf](https://github.com/baselbers/woocommerce-pdf-invoices/files/2420849/admin.side.pdf)

[client side.pdf](https://github.com/baselbers/woocommerce-pdf-invoices/files/2420845/client.side.pdf)

**Comment by SaraAmrousy** [comment]
@baselbers
@dannyvankooten 
@anhducbkhn 
@girogiro 
can you please help me

**Comment by dannyvankooten** [comment]
Hmmmm, some kind of content encoding issue perhaps, @baselbers? Hard to tell, my Arabic isn't as good as it used to be. 😉

**Comment by SaraAmrousy** [comment]
problem is the same content appear correct in admin invoice and messy in customer invoice

**Comment by baselbers** [comment]
Did you managed to work it out? Can I still help you out?

**Comment by mujuonly** [comment]
Is this fixed?

**Comment by roaamagdy** [comment]
I am facing the same problem, any guide how to fix it please?
