### ISSUE TITLE
Is there a way to display vendor name in invoice?

### ISSUE THREAD

**Issue by AbdulRazak02** [baselbers/woocommerce-pdf-invoices#256]
Hi, 
Thanks for the awesome plugin. 
I am running a multi-vendor woocommerce website, in which I need to display the vendor name of each product in the invoice.  And the plugin I use for multi-vendor is Woocommerce Product Vendors.

Can anyone please help me to achieve this ??

Thanks.

**Comment by baselbers** [comment]
Where on the invoice would you like to add the vendor name? You can ask the author of the Woocommerce Product Vendors on how to get the vendor name. I will be happy to help you out.
