### ISSUE TITLE
No date/subscription-range on invoices from WooCommerce Subscriptions

### ISSUE THREAD

**Issue by msbt** [baselbers/woocommerce-pdf-invoices#257]
As the title suggests: On invoices from a subscription-based shop, it will onyl show the product, quantity and price for the single items, but it doesn't include the timeframe for which they got purchased. Ideally it would include "Price / subscription period" on the invoice, so that the customers know for how long they paid.

I've tried poking around with the meta names from https://docs.woocommerce.com/document/subscriptions/develop/data-structure/ (_subscription_period etc) but couldn't get anywhere.

Any pointers on how to get there?

Cheers

**Comment by baselbers** [comment]
My apologies for my late reply. Did you got this to work?

**Comment by msbt** [comment]
Hey, Thanks for getting back to me, but I'm afraid I moved to a different plugin because I couldn't get it to work.
