### ISSUE TITLE
Error in Arabic language

### ISSUE THREAD

**Issue by AbdulRazak02** [baselbers/woocommerce-pdf-invoices#259]
Hello there, 
Thanks for the awesome plugin. I got a small issue while generating pdf invoice in arabic language.
Arabic words are not rendered in a proper way when pdf is generated while the use makes an order.
For example if we have a word like this (  سبتمبر ) then its rendered in the pdf as ( س ب ت م ب ر), but if I try to regenerates it from the admin section then it works fine.

Its already reported in the issue list but its closed. 
(https://github.com/baselbers/woocommerce-pdf-invoices/issues/247)

Can you please help me out to fix this?

Thanks.

**Comment by baselbers** [comment]
We are not sure how to reproduce this error. Can you let me know which PDF reader you are using?
You could have a look in the wiki mpdf.github.io and contact the author of the mPDF library.
https://github.com/mpdf/mpdf/issues/1120

**Comment by leonmuhic** [comment]
Could you send me the woo-commerce system report status? We've tried to reproduce the error, however it's working on our side.

**Comment by roaamagdy** [comment]
Hello,
I have the same issue, could you please mention how you fixed it?
