### ISSUE TITLE
Notice asking for star rating appears right away.

### ISSUE THREAD

**Issue by dannyvankooten** [baselbers/woocommerce-pdf-invoices#47]
I installed the plugin on a fresh install and got the "You are working with WooCommerce PDF Invoices for some time now." notice right after activating the plugin.

![image](https://cloud.githubusercontent.com/assets/885856/11675215/93f6c098-9e5a-11e5-9cd1-ed26142d15b0.png)

**Comment by baselbers** [comment]
Fixed it.

**Comment by dannyvankooten** [comment]
Yeah buddy, Merry Christmas! :santa:
