### ISSUE TITLE
Unable to generate invoice for one order

### ISSUE THREAD

**Issue by jvvlimme** [baselbers/woocommerce-pdf-invoices#48]
I have these one order for which I'm unable to generate an invoice:

I'm running the latest version of WP, WC and WPDF Invoices Premium:

Screenshot of the order:
![order](https://cloud.githubusercontent.com/assets/977885/11897525/ab8586d0-a590-11e5-8aef-87bb9d4fd5fb.PNG)

Screenshot of what is "generated" after I push the button:

![generated](https://cloud.githubusercontent.com/assets/977885/11897552/fcd2437a-a590-11e5-9636-3eb97e41bb49.PNG)

It's only this specific order that is causing problems.  For all others, there is no issue.

**Comment by boyke** [comment]
One of my customers is also having problems with some specific invoices.

**Comment by baselbers** [comment]
Please enable WP_DEBUG and tell me what errors you got.

Which version are you using of the Premium plugin? You can download the latest version from your account from wcpdfinvoices.com/my-account.
