### ISSUE TITLE
"Access denied" bug introduced in ver 2.3.15

### ISSUE THREAD

**Issue by girogiro** [baselbers/woocommerce-pdf-invoices#49]
There is a bug that blocks access to invoices for admin, introduced in last ver. 2.3.15:

In `/includes/be_woocommerce_pdf_invoices.php` in method `invoice_actions()` on line

``` if ( ! is_admin() || get_current_user_id() != $is_customer_order ) ```

there should be && instead of ||.

**Comment by baselbers** [comment]
I've fixed it in 2.3.17. Thanks. :)
