### ISSUE TITLE
Logo size not correct

### ISSUE THREAD

**Issue by boyke** [baselbers/woocommerce-pdf-invoices#51]
Since the last update to 2.3.14 the logo is not displayed correctly. It's larger then it's original size.

**Comment by baselbers** [comment]
Try to change code in file <a href="https://github.com/baselbers/woocommerce-pdf-invoices/blob/master/includes/abstracts/abstract-bewpi-invoice.php">abstract-bewpi-invoice.php</a> from

```$image_url = image_to_base64( $image_url );```
to
```$image_url = '..' . str_replace( get_site_url(), '', $image_url );```

Or if you need to base64 encode the image, just a max-height or max-width to style.css in template.
