### ISSUE TITLE
Use logo from Media Library instead of custom upload

### ISSUE THREAD

**Issue by cristiansavaro** [baselbers/woocommerce-pdf-invoices#54]
I saw that you don't use the media library to add a logo but manually request for the file and store it in wp-content/uploads/year/month/logo-file. Some of us use the media library with aws-s3 cloud storage so nothing is uploaded in the local path. Could you switch to media library storage so we can all benefit from it ?

**Comment by baselbers** [comment]
Thanks for letting me know. Will try to add it in the future.

**Comment by baselbers** [comment]
This has been resolved.
