### ISSUE TITLE
admin.css line 88 breaks WP profile page layout

### ISSUE THREAD

**Issue by shawaj** [baselbers/woocommerce-pdf-invoices#55]
Line 88 of woocommerce-pdf-invoices/assets/css/admin.css with id color-picker causes a brekage on the default wordpress admin colour picker on the "my profile" page.

This should be changed to a different id so that it does not cause interference with standard functionality....suggest changing to invoice-color-picker or similar

![csserror](https://cloud.githubusercontent.com/assets/3359418/12309628/aa09855a-ba43-11e5-88b9-ed602f1ddfdb.png)

**Comment by shawaj** [comment]
actually, after further investigation, I am not sure what this is actually used for in the invoices plugin? Seems like it could be removed completely?

**Comment by baselbers** [comment]
Thanks for letting me know. This will be fixed in the next update. You can also request for a pull
