### ISSUE TITLE
Download invoice from View Order page

### ISSUE THREAD

**Issue by Arkymedes** [baselbers/woocommerce-pdf-invoices#6]
Hello,

It would be nice to have the option to generate the invoice from the View Order page in case the customer deletes the email and needs the invoice for some reason.

It happened a couple of times that I had to manually send the invoice via email to customers.

Thanks a lot and success with your plugin!

**Comment by baselbers** [comment]
I've added this feature and much more in 2.2.0. Let me know if you like it. 
Could you be so kind to [rate](https://wordpress.org/support/view/plugin-reviews/woocommerce-pdf-invoices?rate=5#postform) my plugin. It will only take some seconds. Many thanks!
