### ISSUE TITLE
Bulk download/export invoices

### ISSUE THREAD

**Issue by dannyvankooten** [baselbers/woocommerce-pdf-invoices#62]
Export invoices from Order overview page (using bulk actions) or from custom date range form to a `.zip` file and maybe even create a schedule task for all paid invoices.

https://wordpress.org/support/topic/extraction-of-the-pdf-invoices/
https://wordpress.org/support/topic/awesome-plugin-2193/

**Comment by baselbers** [comment]
+1

https://wordpress.org/support/topic/extraction-of-the-pdf-invoices/

**Comment by baselbers** [comment]
👍

**Comment by baselbers** [comment]
This has been implemented in [Premium ](http://wcpdfinvoices.com/)plugin.
