### ISSUE TITLE
Incorrect treatment of EU VAT plugin

### ISSUE THREAD

**Issue by shawaj** [baselbers/woocommerce-pdf-invoices#69]
Hi,

I think technically, when WooCommerce EU VAT plugin removes the VAT from a transaction due to customer having a valid VAT number, it should say on it "Zero rated for VAT as customer has supplied EU VAT number" and also should show a VAT percentage of 0% and a VAT amount of zero.

The reason for this, is that in EU there are two ways to not charge VAT - zero rated (0%) and Not Applicable (N/A). A zero rated supply is classed as being a VATable supply but with a VAT rate of 0% whereas N/A is just classed as outside of the scope of VAT. It sounds stupid but that is just the way it is.

For zero rated we need to show that there _IS_ VAT on the order, but that it is at 0%.

Hope that makes sense!

**Comment by baselbers** [comment]
Hi,

I've added notice and VAT with 0% on pdf invoice. It will be displayed when VAT number is valid. Hope this suits your needs?

010e6d587539fce975f7bdb2b1f05ef1c43caa8e
