### ISSUE TITLE
Displaying shipping adress / variable product details

### ISSUE THREAD

**Issue by zorensen** [baselbers/woocommerce-pdf-invoices#7]
First of all; Great plugin! I love it and it works perfectly.

However, I would need some changes/enhancements.
When a user doesn't supply a billing adress, but just a shipping adress - no adress is displayed in the PDF. If a user doesn't give a billing adress, but just a shipping adress - the PDF should display the shipping adress. Now it just displays the name with no adress at all on the PDF.

Also, I have some variable products. Is it possible to have the details of the variable product on the line underneath the product name? For examle:

PRODUCT NAME
20 kilos

Thanks for the help and this awesome plugin!

**Comment by zorensen** [comment]
I was able to display the shipping adress on the PDF by adding this line;
<?php echo $this->order->get_formatted_shipping_address(); ?>

However, this displays the name of the costumer two times and that doesn't look so good.

**Comment by baselbers** [comment]
Thanks! 
I will try to add the shipping address and the details of a variable product. Will put it in an update. At the moment I'm also busy adding item tax as a column and many more.

**Comment by zorensen** [comment]
Great! Look forward to it!
Thanks for the quick reply :-)

**Comment by baselbers** [comment]
Try 2.1.0.
Tell me what you think about it. :)

**Comment by zorensen** [comment]
Will do!
Are you interested in a norwegian translation of the plugin? :)

I've translated the plugin already....

**Comment by zorensen** [comment]
Awesome! :)
This is just what I was looking for. Thanks for the quick turnaround on this.

Do you have a updated language file, so all the strings easily can be translated?

**Comment by zorensen** [comment]
The field "Billing adress" and "Order adress" isn't translated. Also the ordernumber and orderdate on the PDF aren't translated. In the footer I have this "Payment via" line that also should be translated :)

**Comment by baselbers** [comment]
Please send me you Norwegian language files. I will look into the translations. Thanks!
Would you be so kind to <a src="https://wordpress.org/support/view/plugin-reviews/woocommerce-pdf-invoices?rate=5#postform">rate</a> the plugin?

**Comment by zorensen** [comment]
Sure! :-)
Where do I send the language files?

**Comment by baselbers** [comment]
Language files to baselbers@hotmail.com.

Rate the plugin at https://wordpress.org/support/view/plugin-reviews/woocommerce-pdf-invoices?rate=5#postform

**Comment by baselbers** [comment]
Did you send me the language files? Think I didn't receive any.
