### ISSUE TITLE
All product metadata is shown on invoice MIGHT SHOW SENSITIVE INFORMATION

### ISSUE THREAD

**Issue by EmilEriksen** [baselbers/woocommerce-pdf-invoices#71]
In the product lines all meta is shown. See [here](https://github.com/wp-plugins/woocommerce-pdf-invoices/blob/master/includes/templates/invoices/simple/micro/body.php). This is both unnecessary as it might clutter the invoice and it might add sensitive information. I just installed WooCommerce Cost of Goods today and as a result the cost of our products was added to a few of our customers invoices.

**Comment by baselbers** [comment]
Hi,

Thanks for letting me know. The "WooCommerce Cost of Goods" plugin is only hiding these meta within admin, but not on public area of website. I've added them manually in code.

1ec5784321fc58896753dd6077488641a1cd2559
