### ISSUE TITLE
Automatically Generate PDF invoice

### ISSUE THREAD

**Issue by mkhandouzy** [baselbers/woocommerce-pdf-invoices#72]
Hi, This an awesome plugin that I really love it.
Simple, Easy, Compatible (RTL Languages and Unicode char-sets)

But the only issue is, there is no automatic PDF generating, I want my customers to be able download the PDF invoice from their "my-account" page without admin intervention. If an order was paid successful, customer should be able to download the PDF invoice.

I'm really looking forward to this enhancement :+1: 
Best Regards,

**Comment by adiardana** [comment]
@mkhandouzy : have you check the download options on the plugins setting page? i think it has the option to show the download button in the customer account page. And it's only showed if the order status is 'completed'

**Comment by baselbers** [comment]
@adiardana is right. You can try the customer download option on settings page.
