### ISSUE TITLE
Any way to display customer invoice total?

### ISSUE THREAD

**Issue by kschmick** [baselbers/woocommerce-pdf-invoices#8]
I'm using a combination of MemberMouse and WooCommerce to setup an online shop for dealers and distributors to purchase parts from us. I'm trying to use your invoice plugin as a way to bill these customers for service repair on their products. I'm just wondering if there is a way to display an invoiced total on their "My Account" page as an additional reminder that they owe money? Or, if nothing else, is their a way to post their invoices on their "My Account" page so they see all of their recent invoices?

Thanks!

**Comment by baselbers** [comment]
Hello,
I've bin away for some days. This would be a nice feature. Will add this feature as soon as possible.

**Comment by baselbers** [comment]
Update to 2.2.0 and let me know if you like it.

**Comment by kschmick** [comment]
I think that exactly accomplishes what I was after. This shall make it much easier for folks to login and pay an invoice if they lost the email. Great work and thanks!

**Comment by baselbers** [comment]
Great to hear! Would you be so kind to [rate](https://wordpress.org/support/view/plugin-reviews/woocommerce-pdf-invoices?rate=5#postform) the plugin? I would appreciate it very much.
