### ISSUE TITLE
Check if product is not deleted/removed before generating invoice

### ISSUE THREAD

**Issue by KloonDuino** [baselbers/woocommerce-pdf-invoices#83]
`Fatal error: Uncaught Error: Call to a member function get_title() on boolean in /home/xxx/public_html/wp-content/plugins/woocommerce-pdf-invoices/includes/templates/invoices/simple/micro/body.php:80 Stack trace: #0 /home/xxx/public_html/wp-content/plugins/woocommerce-pdf-invoices/includes/abstracts/abstract-bewpi-invoice.php(473): require_once() #1 /home/xxx/public_html/wp-content/plugins/woocommerce-pdf-invoices/includes/abstracts/abstract-bewpi-invoice.php(197): BEWPI_Abstract_Invoice->output_to_buffer('/home/microkloo...') #2 /home/xxx/public_html/wp-content/plugins/woocommerce-pdf-invoices/includes/abstracts/abstract-bewpi-invoice.php(350): BEWPI_Abstract_Invoice->output_template_files_to_buffer(Array) #3 /home/xxx/public_html/wp-content/plugins/woocommerce-pdf-invoices/includes/class-bewpi-invoice.php(70): BEWPI_Abstract_Invoice->save('F', Array) #4 /home/xxx/public_html/wp-content/plugins/woocommerce-pdf-invoices/includes/be-woocommerce-pdf-invoices.php(217): BEWPI_Invoice- in /home/xxx/public_html/wp-content/plugins/woocommerce-pdf-invoices/includes/templates/invoices/simple/micro/body.php on line 80`

**Comment by baselbers** [comment]
Are you trying to generate a PDF Invoice for a product that does not exist anymore?
Are you using some additional WooCommerce plugins?

**Comment by KloonDuino** [comment]
as was in the initial report: this happens when a pdf is made for an invoice where a credit was applied. So in a sense, yes there was an item deleted (the credited item), but it should still be on the invoice.

**Comment by MicroKloon** [comment]
is it fixed?

**Comment by baselbers** [comment]
Yes. :)
