### ISSUE TITLE
Move custom templates from uploads to themes folder

### ISSUE THREAD

**Issue by baselbers** [baselbers/woocommerce-pdf-invoices#96]

**Comment by baselbers** [comment]
https://github.com/baselbers/woocommerce-pdf-invoices/commit/cb917e9a83fc3c762b82790919031d5fec71a0eb

**Comment by smilingpeanut** [comment]
Taking a look at this commit doesn't seem to allow for the templates to be placed in the theme directory. Can you advise how to achieve this? Thanks!

**Comment by baselbers** [comment]
You can use below filter to add your own directories.
https://github.com/baselbers/woocommerce-pdf-invoices/blob/v2.9.3/includes/class-template.php#L81

**Comment by smilingpeanut** [comment]
Thank you!

**Comment by lewebsimple** [comment]
The filter doesn't work when updating the template from the admin as the form action calls `wp-admin/post.php` and so the theme isn't loaded
